### PR TITLE
add logo of Angular challenges

### PR DESCRIPTION
**Pull request by tomalaforge**
## Checklist for logo submission

- [ ] Logo file added to the `logos` folder
- [ ] Created a new entry in `metadata.json` (only `name` is mandatory)
- [ ] Logo is an SVG with vector paths (no embedded pixel image)
- [ ] The logo fills the image and there is no white margin (please remove the white margin if there is any 🙂 )

### CODE REVIEW

**Comment by fmalcher** [comment]
Thanks for the submission! @tomalaforge 
Do you have a real vector version of this? The current one is a PNG embedded in SVG. Also, please remove the white margin around the logo. Thanks! 😊

**Comment by tomalaforge** [comment]
Hi @fmalcher , 
Do you have an app to transform png to svg. I've tried a lot, but couldn't do it better than the svg I sent. 
And Ok for the margin. I'll do it.

**Comment by fmalcher** [comment]
>  Do you have an app to transform png to svg. I've tried a lot, but couldn't do it better than the svg I sent.

That's fine then! 🙂

**Comment by tomalaforge** [comment]
I removed the white borders, hope the logo is ok now ?

**Review by fmalcher — APPROVED** [review]

**Comment by fmalcher** [comment]
Here we go! https://angularlogos.com/?q=Challenges

**Comment by maartentibau** [comment]
Thanks!! 🙏 @fmalcher @tomalaforge

**Pull request merged**
