### PR TITLE
feat(logos): add angular malaga logo

### PR DESCRIPTION
**Pull request by NyaGarcia**

### CODE REVIEW

**Comment by maartentibau** [comment]
Hi,

Would you be able to answer these questions:

- Name
- Description
- License 
- Website

If you don’t know, no prob 🙂

**Comment by NyaGarcia** [comment]
Hi, 
Of course, didn't realize I had to add any info, sorry :sweat_smile: 
Name: Angular Malaga
Description: The Angular Malaga logo, featuring the beautiful Cathedral of Malaga
License: MIT
Website: http://angularmalaga.com

Thanks!

**Comment by maartentibau** [comment]
It is not “obligated” we just kindly ask, but we have not yet modified the PR template, so you could not have known 🙂

**Comment by maartentibau** [comment]
Oh sorry... forgot one question 

Who created it?

**Comment by NyaGarcia** [comment]
I created it. Estefania garcia gallardo, in case you need my full name. 
Thank you 😊

**Comment by maartentibau** [comment]
I'm not sure about the web address, when I browse to it, I get redirected to a page to login to my Google account.

**Pull request merged**
