### PR TITLE
Angular Kharkiv Community Logo

### PR DESCRIPTION
**Pull request by LimarenkoDenis**

### CODE REVIEW

**Comment by fmalcher** [comment]
LGTM, thanks! If you have a way to edit the SVG, can you remove the margin, please? 🙂 @LimarenkoDenis

**Comment by LimarenkoDenis** [comment]
@fmalcher Lazy to ask designer ) Please approve if it is not critical)

**Comment by fmalcher** [comment]
It's not a show-stopper, but it would be really nice to have all margin-less logos. I removed the margin for you, please submit the file in your PR. Thanks! @LimarenkoDenis 


[angular-kharkiv.svg.zip](https://github.com/maartentibau/angular-logos/files/5719236/angular-kharkiv.svg.zip)

**Comment by maartentibau** [comment]
I created a PR myself 😄 https://github.com/maartentibau/angular-logos/pull/94
This one can be close then

**Pull request closed without merging**
