### PR TITLE
fix: delete deprecated codelyzer's logo

### PR DESCRIPTION
**Pull request by jdegand**
I don't think it is included in the json, but it shows up on the main page.   Removed earlier ?

### CODE REVIEW

**Comment by fmalcher** [comment]
The JSON file was introduced later and it doesn't have to be complete. 🙂 The website shows all logos from the repo and adds the metadata from the JSON file.

I don't know how I feel about removing the logo. I see this project as some kind of archive and tend to keep old logos. What do you think, @maartentibau ?

**Comment by jdegand** [comment]
I'd suggest you remove all the interactive links or make a separate section for legacy repos.  I want to search and find relevant Angular info.

**Comment by fmalcher** [comment]
My perception of the original idea of this project was to conserve logo artwork that evolved from the Angular logo. To me, it was never meant to be a resource listing for Angular-related projects. Just a list of logos, nothing more and nothing less. 🙂
I'm looking forward to @maartentibau 's take on this!

Dead links should indeed be removed. PR's are appreciated!

**Comment by d-koppenhagen** [comment]
From my point of view a "legacy" section would not be beneficial. I think this project simply helps to find the logos for specific Angular libs. I think it's not like an Awesome-List like [this one](https://github.com/PatrickJS/awesome-angular).
The description at angularlogos.com also clearly focusses on collecting logos:

> Welcome to Angular Logos – a website dedicated to collecting all logos and badges that are inspired by the original Angular logo.
The logos that can be found on this website can be related to conferences, Meetup groups, NPM packages or anything else that exists within the Angular universe.

**Comment by jdegand** [comment]
Simplest fix: add website metadata for all current projects and deprecated projects don't get a website url.  Remove the website url for Angular Three, but that's it.  'ngx-code-gen' is in limbo so leave that url as well.  And make sure any new logos added have metadata as well.

**Pull request closed without merging**
