### PR TITLE
Timdeschryver patch 1

### PR DESCRIPTION
**Pull request by timdeschryver**
## Checklist for logo submission

- [x] Logo file added to the `logos` folder
- [x] Created a new entry in `metadata.json` (only `name` is mandatory)
- [x] Logo is an SVG with vector paths (no embedded pixel image)
- [x] The logo fills the image and there is no white margin (please remove the white margin if there is any 🙂 )

Huge props to @goetzrobin

### CODE REVIEW

**Comment by fmalcher** [comment]
Thanks! Do you have a transparent version of the logo without the dark background? Or do you always use the logo as a dark square, even on lighter backgrounds? @timdeschryver @goetzrobin

**Comment by timdeschryver** [comment]
@fmalcher we do have a transparent logo now 😉

**Comment by fmalcher** [comment]
Great! Nit: If you have the chance to remove the margin around the image, it will fit better into the box on the website.
If you don't want to change it, we'll take it with the margin. Thanks!

**Comment by timdeschryver** [comment]
Woops sorry, forgot about that @fmalcher .
It's cropped and minified now.

**Comment by maartentibau** [comment]
Thank you @timdeschryver 🙏🙏

**Pull request merged**
