### PR TITLE
add thoughtram's logo

### PR DESCRIPTION
**Pull request by manolof**

### CODE REVIEW

**Comment by maartentibau** [comment]
Maybe change the colors of the Angular badge to match the colors of the Thoughtram colors?

**Comment by maartentibau** [comment]
Why did you close the request? I really liked it, want me to reopen it?

**Comment by manolof** [comment]
No worries, thoughtram requested something different, so I will reopen once I have his approval ;)

**Comment by maartentibau** [comment]
OK, great!

**Pull request closed without merging**
