### PR TITLE
Add Angular Birmingham UK logo

### PR DESCRIPTION
**Pull request by alexcotelin**

### CODE REVIEW

**Comment by fmalcher** [comment]
LGTM

**Comment by fmalcher** [comment]
Thank you for the PR! Can you please crop the logo so it doesn't have any white margins? @alexcotelin

**Comment by maartentibau** [comment]
I currently have an issue when I try to preview the SVG. Don't know if it has anything to do with those white margins or something else.

image

**Comment by fmalcher** [comment]
Works pretty good for me 😅

Screen Shot 2020-05-17 at 13 40 00

**Comment by alexcotelin** [comment]
> Thank you for the PR! Can you please crop the logo so it doesn't have any white margins? @alexcotelin

Sure, will do

**Comment by maartentibau** [comment]
@alexcotelin can you have a final look at this please and resolve the merge conflict if possible.
If you need any help, please let me know.

**Comment by alexcotelin** [comment]
Yes, waiting for the cropped image and I'll add it

**Review by fmalcher — APPROVED** [review]
LGTM, thank you!

**Comment by maartentibau** [comment]
Thank You 🙏

**Pull request merged**
