### PR TITLE
feat: add ngx-aws-deploy logo

### PR DESCRIPTION
**Pull request by Jefiozie**
As mentioned here by the ngx-aws-deploy logo.
Thanks @maartentibau

### CODE REVIEW

**Comment by fmalcher** [comment]
@Jefiozie Thank you! The SVG looks technically good, but can you remove the white margins please? 😎

**Comment by Jefiozie** [comment]
Hi @fmalcher I removed the big margins around it, is this the resolution you're looking for?

**Review by fmalcher — APPROVED** [review]
Yes, thank you! LGTM.

**Comment by maartentibau** [comment]
Thanks!! 🙏

**Pull request merged**
