### PR TITLE
add original Angular logos

### PR DESCRIPTION
**Pull request by fmalcher**

### CODE REVIEW

**Comment by maartentibau** [comment]
I personally don’t really think the actual Angular logos belong in this repo.

Also, the file names should be pascal-case.

**Comment by fmalcher** [comment]
Oh really? When I read the intro text "inspired on the original Angular logo" I had the impulse to link to the original logo. I really liked the idea that the Angular logo is always first in the list, like the original octocat is first in the [Octodex](https://octodex.github.com/) (expect for that this is reverse sorted).

Do the logo variants (inverted and B/W) also not belong to the repo?
What about the [brand icons](https://angular.io/presskit#brand-icons) that are also official?

**Comment by JohannesHoppe** [comment]
Of course, at least the red Angular logo must be included. That goes without saying!

**Comment by maartentibau** [comment]
> Of course, at least the red Angular logo must be included. That goes without saying!

I would be OK with adding the original logos, but not to the list. I would add them to the angularlogos.com website, maybe on a separate page or some toggle pane/box so that people can easily download them if they want, like now can be done on the PressKit of Angular.

**Pull request closed without merging**
