### PR TITLE
Recreated in vector

### PR DESCRIPTION
**Pull request by webmaxru**

### CODE REVIEW

**Comment by maartentibau** [comment]
The only doubt I have is with the very large viewBox. Don’t know if the has an effect on displaying it on the website.

**Comment by fmalcher** [comment]
Thanks, maxim! yes, should be cropped

**Review by fmalcher — CHANGES_REQUESTED** [review]
Thanks, maxim! yes, should be cropped

**Comment by fmalcher** [comment]
Closed in favor of #96

**Pull request closed without merging**
