### PR TITLE
add ng turkey logo

### PR DESCRIPTION
**Pull request by armanozak**

### CODE REVIEW

**Comment by maartentibau** [comment]
Thank you 🙏

**Comment by armanozak** [comment]
Hey @maartentibau, 

I have checked the logo and it is getting a 404. Is there a pipeline involved?

**Comment by maartentibau** [comment]
> Hey @maartentibau,
> 
> I have checked the logo and it is getting a 404. Is there a pipeline involved?

Every time we merge a new logo a build is being done by GitHub to generate the GHPages of this repo, this always takes a few minutes.

But the Angular Logos websites queries the folder structure of the repo to generate the list of logos, so that one is already updated right after the merge with master.

It might be a good idea to check IF we can prevent this.

**Comment by armanozak** [comment]
It may be difficult to prevent this completely, but hiding the mat-card component until successful load of image may provide a quick solution. The request will still get a 404, but at least nobody will see an errored image element. 🤷‍♂

**Comment by maartentibau** [comment]
Indeed, I created a ticket for it https://github.com/maartentibau/angularlogoscom/issues/18

**Pull request merged**
