### PR TITLE
chore: add ng logos by @tinesoft

### PR DESCRIPTION
**Pull request by tinesoft**

### CODE REVIEW

**Comment by maartentibau** [comment]
@tinesoft I would also love to have the cookieconsent logo if possible 😄 
Could you also maybe adobt the `metadata.json` file if possible?

**Comment by tinesoft** [comment]
Hi @maartentibau 

Done!

I rename/update the current `ngx-cookie-consent` into `ngx-cookieconsent` (to match my project name).
I also update the `metadata.json` file. Maybe add theses instructions on the [README](https://github.com/maartentibau/angular-logos#how-to-submit-a-logo) page for future PRs?

**Comment by maartentibau** [comment]
> Hi @maartentibau
> 
> Done!
> 
> I rename/update the current `ngx-cookie-consent` into `ngx-cookieconsent` (to match my project name).
> I also update the `metadata.json` file. Maybe add theses instructions on the [README](https://github.com/maartentibau/angular-logos#how-to-submit-a-logo) page for future PRs?

Thx! 😄 ... I'll update the Readme, good remarks!

**Comment by tinesoft** [comment]
A PR template would be great as well (as suggested here https://github.com/maartentibau/angular-logos/issues/65)

**Comment by fmalcher** [comment]
Hi @tinesoft , thank you for the contribution! Can you please remove the margin around the logos? Thanks!

**Comment by tinesoft** [comment]
Hi @fmalcher,

Sorry for the delay! The logos have been cleaned up.
Cheers!

**Review by fmalcher — APPROVED** [review]
Great, thank you! LGTM

**Comment by maartentibau** [comment]
Thank you 🙏

**Pull request merged**
