### PR TITLE
feat: add Angular After Dark logo

### PR DESCRIPTION
**Pull request by LayZeeDK**
Add the logo for [Angular After Dark](https://www.youtube.com/playlist?list=PLyY4r1b00A5DeSkFHJXu5OJc-5rVk7Uvk).

### CODE REVIEW

**Comment by fmalcher** [comment]
Thanks Lars! Can you remove the white margin around the logo, please? 🙂

**Comment by LayZeeDK** [comment]
I have no graphical editor. I'm hand-coding. The latest commit is the best I can do without a proper graphical editor.

**Comment by fmalcher** [comment]
LGTM, thank you! 🙂 It's not really about getting a zero-width margin but rather to not have a visible large margin that makes the actual logo smaller in the viewbox.

**Review by fmalcher — APPROVED** [review]

**Comment by maartentibau** [comment]
Thank you 🙏

**Pull request merged**
