### PR TITLE
add: angular three logo

### PR DESCRIPTION
**Pull request by nartc**
## Checklist for logo submission

- [x] Logo file added to the `logos` folder
- [x] Created a new entry in `metadata.json` (only `name` is mandatory)
- [x] Logo is an SVG with vector paths (no embedded pixel image)
- [x] The logo fills the image and there is no white margin (please remove the white margin if there is any 🙂 )

### CODE REVIEW

**Comment by fmalcher** [comment]
Hi Chau, can you please remove the margin around the logo? Thank you! 🙂

**Comment by nartc** [comment]
@fmalcher Used the wrong logo 🤦‍♂️. Pushed the update, can you please double check?

**Comment by fmalcher** [comment]
Cool thanks, LGTM 😇

**Comment by maartentibau** [comment]
Thanks @nartc 🙏

**Pull request merged**
