### PR TITLE
Added ng-Keralam Logo

### PR DESCRIPTION
**Pull request by SuhasParameshwara**

### CODE REVIEW

**Comment by fmalcher** [comment]
Thank you fo the submission! Can you please remove the margin around the logo? 🙂 @SuhasParameshwara

**Comment by SuhasParameshwara** [comment]
@fmalcher Sure. I'll do it as soon as possible.

**Comment by maartentibau** [comment]
@SuhasParameshwara any update?

**Comment by maartentibau** [comment]
@fmalcher If you remove the margin I will create a PR if you like, than this one can be closed as well

**Comment by fmalcher** [comment]
Closed in favor of #97

**Pull request closed without merging**
