### PR TITLE
add angular apac logo

### PR DESCRIPTION
**Pull request by queency-koh**
## Checklist for logo submission

- [ ] Logo file added to the `logos` folder
- [ ] Created a new entry in `metadata.json` (only `name` is mandatory)
- [ ] Logo is an SVG with vector paths (no embedded pixel image)
- [ ] The logo fills the image and there is no white margin (please remove the white margin if there is any 🙂 )

### CODE REVIEW

**Comment by fmalcher** [comment]
Thanks for the submission! @queency-koh 
Unfortunately, I can't open the file in any browser... looks like it's corrupted. From the sourcecode it looks like a PNG embedded into SVG. Do you have a "real" vectorized version of the logo?

**Comment by queency-koh** [comment]
> Thanks for the submission! @queency-koh 
> 
> Unfortunately, I can't open the file in any browser... looks like it's corrupted. From the sourcecode it looks like a PNG embedded into SVG. Do you have a "real" vectorized version of the logo?

I do not have a "real" vectorized version. I will try to recreate it.

**Comment by queency-koh** [comment]
Hi @maartentibau I have a new commit. I replaced the old logo with a vectorized version.

**Review by fmalcher — APPROVED** [review]
Thank you! 🙂

**Comment by maartentibau** [comment]
Thanks!! 😊

**Pull request merged**
