### PR TITLE
feat: add ngx-doc-gen

### PR DESCRIPTION
**Pull request by bohoffi**
## Checklist for logo submission

- [X] Logo file added to the `logos` folder
- [X] Created a new entry in `metadata.json` (only `name` is mandatory)
- [X] Logo is an SVG with vector paths (no embedded pixel image)
- [X] The logo fills the image and there is no white margin (please remove the white margin if there is any 🙂 )

### CODE REVIEW

**Comment by fmalcher** [comment]
Thanks @bohoffi ! 🙂 Can you please remove the margin around the logo?

**Comment by fmalcher** [comment]
Interestingly, GitHub displays the logo with a top and bottom margin while the logo file is actually fine … sorry, all good here! 😄 

Screenshot 2022-11-11 at 21 18 11

**Review by fmalcher — APPROVED** [review]

**Comment by bohoffi** [comment]
@fmalcher you got me all confused for a moment 😆

**Comment by maartentibau** [comment]
Thank you! 🙏

**Pull request merged**
